from __future__ import annotations

from dataclasses import dataclass


__test__ = False


@dataclass(frozen=True)
class TestCatalogEntry:
    test_id: int
    display_name: str
    evaluates: str


TEST_CATALOG: dict[int, TestCatalogEntry] = {
    1001: TestCatalogEntry(1001, "Protocol CRC known vector", "Frame CRC/TLV decode baseline."),
    1002: TestCatalogEntry(1002, "Protocol frame round trip", "Self-test transport framing and command echo path."),
    1003: TestCatalogEntry(1003, "Status heartbeat", "MCU status stream availability and basic timing."),
    1004: TestCatalogEntry(1004, "Status pause/resume", "Status traffic control while diagnostic commands run."),
    1005: TestCatalogEntry(1005, "Flash configuration", "Firmware flash metadata exposed through diagnostics."),
    1006: TestCatalogEntry(1006, "Build identity", "Firmware build identity and version metadata."),
    1007: TestCatalogEntry(1007, "Flash CRC", "Stored firmware image integrity metadata."),
    1010: TestCatalogEntry(1010, "HELLO handshake", "Host-to-MCU session open handshake."),
    1011: TestCatalogEntry(1011, "GOODBYE handshake", "Host-to-MCU session close handshake."),
    1012: TestCatalogEntry(1012, "Duplicate command handling", "Command sequence duplicate detection behavior."),
    1013: TestCatalogEntry(1013, "Queue ACK details", "Command queue ACK metadata and sequence tracking."),
    1020: TestCatalogEntry(1020, "Status payload fields", "Core status payload field presence and parseability."),
    1021: TestCatalogEntry(1021, "Status timing", "Status frame period and jitter."),
    1030: TestCatalogEntry(1030, "Protocol parser resilience", "Parser handling for malformed or boundary frames."),
    1040: TestCatalogEntry(1040, "Runtime memory margins", "Heap and task stack margin telemetry."),
    1041: TestCatalogEntry(1041, "Reset/crash report path", "Reset report availability and crash-report plumbing."),
    1042: TestCatalogEntry(1042, "Watchdog diagnostic path", "Watchdog diagnostic reporting path."),
    1043: TestCatalogEntry(1043, "Self-test scheduler", "Result-emission scheduling and live pressure-task latency evidence."),
    1044: TestCatalogEntry(1044, "Pressure watchdog context", "Checksummed retained pressure-task phase and I2C evidence."),
    2001: TestCatalogEntry(2001, "Motion homing", "Axis homing success, duration, and limit switch behavior."),
    2002: TestCatalogEntry(2002, "Motion move/return", "Bounded gantry move accuracy and return error."),
    2003: TestCatalogEntry(2003, "Pressure response", "Regulator settle time, overshoot, and steady-state error."),
    2004: TestCatalogEntry(2004, "Valve open/close sequence", "Valve command sequencing and observed open/close counts."),
    2005: TestCatalogEntry(2005, "Valve pulse timing", "Pulse count and pulse-width timing behavior."),
    2006: TestCatalogEntry(2006, "Safety abort", "Abort latency and safe state of motion, pressure, and valves."),
    2007: TestCatalogEntry(2007, "Motion home repeatability", "Repeated homing span and return error for gantry axes."),
    2008: TestCatalogEntry(2008, "Motion pattern return", "Pattern move return accuracy and envelope bounds."),
    2010: TestCatalogEntry(2010, "XY long travel", "Long X/Y travel repeatability across the safe gantry envelope."),
    2011: TestCatalogEntry(2011, "XY raster repeatability", "Small serpentine moves that mimic well-plate printing motion."),
    2012: TestCatalogEntry(2012, "XY long reverse travel", "Reverse-order long X/Y travel repeatability across the safe gantry envelope."),
    2013: TestCatalogEntry(2013, "XY diagonal travel", "Coordinated diagonal X/Y moves between safe envelope corners."),
    2014: TestCatalogEntry(2014, "384-well plate raster", "Operator-confirmed evaporation-plate setup at the plate start, Z lower to 91500, then serpentine 16 x 24 plate raster across the print envelope before Z home and XY return."),
    2015: TestCatalogEntry(2015, "Z long travel", "Repeated Z-axis long travel to 80000 steps from the raster-start XY anchor and back to home."),
    2016: TestCatalogEntry(2016, "Triggered-limit homing", "Homing recovery when X, Y, and Z begin with limit switches already triggered."),
    2020: TestCatalogEntry(2020, "Legacy XY low-rate timing", "6 kHz equal-axis safety probe and baseline ISR/status timing."),
    2021: TestCatalogEntry(2021, "Legacy X-only max-rate timing", "40 kHz X-only ISR entry count, phase-cycle maxima, pending updates, and status scheduling."),
    2022: TestCatalogEntry(2022, "Legacy Y-only max-rate timing", "40 kHz Y-only ISR entry count, phase-cycle maxima, pending updates, and status scheduling."),
    2023: TestCatalogEntry(2023, "Legacy equal-XY max-rate timing", "Simultaneous 40 kHz X/Y legacy ISR load during an equal diagonal."),
    2024: TestCatalogEntry(2024, "Legacy camera/home-ratio timing", "Simultaneous legacy ISR load for a safe-envelope move matching the incident camera-to-home X:Y distance ratio."),
    2025: TestCatalogEntry(2025, "Legacy short-triangular timing", "Short 1000-step X move whose profile cannot reach a sustained cruise phase."),
    2030: TestCatalogEntry(2030, "Normalized cosine LUT timing", "Non-motion target benchmark of fixed-point profile preparation, evaluation, legacy speedup, and ARR compatibility."),
    2040: TestCatalogEntry(2040, "Coordinated XY X-only low-rate", "Gated TIM2-master execution of an X-only coordinated round trip at 3 kHz."),
    2041: TestCatalogEntry(2041, "Coordinated XY Y-only low-rate", "Gated TIM2-master execution of a Y-only coordinated round trip at 3 kHz."),
    2042: TestCatalogEntry(2042, "Coordinated XY equal low-rate", "Gated equal-axis coordinated round trip and straightness observation at 3 kHz."),
    2043: TestCatalogEntry(2043, "Coordinated XY asymmetric low-rate", "Gated asymmetric coordinated round trip and straightness observation at 3 kHz."),
    2044: TestCatalogEntry(2044, "Coordinated XY pause/resume", "Pulse-boundary pause, stable hold, cached-event resume, and return behavior."),
    2045: TestCatalogEntry(2045, "Coordinated XY cancel", "Pulse-boundary cancel latency, position rebasing, safe pins, and legacy recovery."),
    2046: TestCatalogEntry(2046, "Coordinated XY limit abort", "Injected X/Y limit abort forwarding, latency, rebasing, recovery, and post-home drift."),
    2050: TestCatalogEntry(2050, "Normal XY route X-only low-rate", "Normal Gantry::moveTo routing through the coordinated executor for an X-only 3 kHz round trip."),
    2051: TestCatalogEntry(2051, "Normal XY route Y-only low-rate", "Normal Gantry::moveTo routing through the coordinated executor for a Y-only 3 kHz round trip."),
    2052: TestCatalogEntry(2052, "Normal XY route equal low-rate", "Normal equal-axis coordinated route, endpoint agreement, and straightness observation at 3 kHz."),
    2053: TestCatalogEntry(2053, "Normal XY route asymmetric low-rate", "Normal asymmetric coordinated route, endpoint agreement, and straightness observation at 3 kHz."),
    2054: TestCatalogEntry(2054, "Normal XY route long status", "Large-move regulator hold cleanup and status/watchdog cadence while the normal coordinated route runs."),
    2055: TestCatalogEntry(2055, "Normal XY route controls", "Normal-route pause/resume, cancel rebasing, and recovery behavior."),
    2056: TestCatalogEntry(2056, "Normal XY physical limit", "Bounded physical X/Y limit termination, no-later-rise guarantee, rebasing, and home drift."),
    2057: TestCatalogEntry(2057, "Normal XY legacy smoke", "Direct X/Y and Z legacy round trips after coordinated ownership releases."),
    2060: TestCatalogEntry(2060, "Coordinated XY 5 kHz performance", "Five production-geometry forward/reverse pairs with exact pulses, timing, status cadence, and post-tier home drift at 5 kHz."),
    2061: TestCatalogEntry(2061, "Coordinated XY 10 kHz performance", "Five production-geometry forward/reverse pairs with exact pulses, timing, status cadence, and post-tier home drift at 10 kHz."),
    2062: TestCatalogEntry(2062, "Coordinated XY 20 kHz performance", "Five production-geometry forward/reverse pairs with exact pulses, timing, status cadence, and post-tier home drift at 20 kHz."),
    2063: TestCatalogEntry(2063, "Coordinated XY 30 kHz performance", "Five production-geometry forward/reverse pairs with exact pulses, timing, status cadence, and post-tier home drift at 30 kHz."),
    2064: TestCatalogEntry(2064, "Coordinated XY 40 kHz performance", "Five production-geometry forward/reverse pairs with exact pulses, timing, status cadence, and post-tier home drift at 40 kHz."),
    2065: TestCatalogEntry(2065, "Coordinated XY legacy-vector comparison", "Exact Milestone 1 X-only, Y-only, equal, camera-ratio, and short-triangular vectors through the coordinated executor."),
    2066: TestCatalogEntry(2066, "Coordinated XY asymmetric raster", "40 kHz asymmetric round trips and the Z-up 16 by 24 serpentine raster with exact callback/pulse totals and post-raster drift."),
    2067: TestCatalogEntry(2067, "Coordinated XY camera-ratio repeat", "Five 40 kHz camera/home-ratio forward/reverse cycles with exact path and timing evidence."),
    2068: TestCatalogEntry(2068, "Coordinated XY pressure coexistence", "40 kHz camera-ratio round trip while both closed-loop pressure regulators move between accepted 1 and 2 psi targets."),
    2070: TestCatalogEntry(2070, "Coordinated XY X-direction speed isolation", "Home-referenced positive and negative X-only qualification at 30, 35, and 40 kHz with normal and reduced acceleration."),
    2071: TestCatalogEntry(2071, "Coordinated XY camera/home transition", "Cold 40 kHz camera-ratio round trip followed immediately by bounded legacy X homing with enable, timer, STEP, and limit evidence."),
    2072: TestCatalogEntry(2072, "Coordinated XY 40 kHz full IRQ timing", "Earliest TIM2 IRQ entry through HAL callback return timing, correlated with pending-update observations."),
    2073: TestCatalogEntry(2073, "Coordinated XY 40 kHz entry lateness", "TIM2 counter-at-entry and inter-entry schedule lateness captured before HAL dispatch."),
    2074: TestCatalogEntry(2074, "Coordinated XY single-IRQ pulse margin", "One-interrupt-per-step mode, STEP-high width, complete callback coverage, and remaining TIM2 deadline slack."),
    2080: TestCatalogEntry(2080, "Coordinated XY MRES3 20 kHz motion", "Diagnostic MRES=3 ten-move geometry row submitted in legacy logical coordinates with exact native STEP-cycle totals."),
    2081: TestCatalogEntry(2081, "Coordinated XY MRES3 20 kHz IRQ path", "Full two-edge TIM2 IRQ coverage and pending-update evidence for the diagnostic MRES=3 geometry row."),
    2082: TestCatalogEntry(2082, "Coordinated XY MRES3 20 kHz deadline margin", "TIM2 entry-lateness, deadline margin, and diagnostic rearm-from-actual-edge coverage at the 20 kHz step-event rate."),
    2083: TestCatalogEntry(2083, "TMC2208 MRES3 configuration", "Readback-independent evidence that the diagnostic image initialized the shared TMC2208 UART configuration for MRES=3, DEDGE enabled, and multistep filtering disabled."),
    2086: TestCatalogEntry(2086, "Coordinated XY conditional late rearm", "Diagnostic-only TIM2 decisions, injected late-edge recovery, non-rearmed slack, and schedule-policy saturation evidence."),
    2087: TestCatalogEntry(2087, "Production MRES3 coordinated motion", "Production MRES=3 ten-move row using legacy logical coordinates and exact native STEP-cycle totals."),
    2088: TestCatalogEntry(2088, "Production MRES3 IRQ path", "Full two-edge TIM2 IRQ coverage for production MRES=3 coordinated motion."),
    2089: TestCatalogEntry(2089, "Production conditional late rearm", "Production conditional-rearm decisions, deadline margin, and recovered late-service evidence without synthetic injection."),
    2090: TestCatalogEntry(2090, "Production TMC2208 MRES3 configuration", "Production MRES=3, DEDGE, multistep-filter, and legacy logical-unit conversion evidence."),
    2098: TestCatalogEntry(2098, "Coordinated XY motion-limit debounce", "Continuous 15 ms X/Y motion-limit confirmation, transient rejection, timebase, and terminal-reason evidence."),
    2091: TestCatalogEntry(2091, "Direct X normalized LUT", "Ordinary direct X cruise-capable motion using the fixed-point normalized cosine profile with exact native pulses and ISR timing."),
    2092: TestCatalogEntry(2092, "Direct Y normalized LUT", "Ordinary direct Y cruise-capable motion using the fixed-point normalized cosine profile with exact native pulses and ISR timing."),
    2093: TestCatalogEntry(2093, "Direct Z normalized LUT", "Ordinary direct Z cruise-capable motion using the fixed-point normalized cosine profile and exact endpoint evidence."),
    2094: TestCatalogEntry(2094, "Direct X triangular LUT", "Short direct X triangular motion using the fixed-point normalized cosine profile with complete cursor coverage."),
    2095: TestCatalogEntry(2095, "Direct LUT isolation", "Homing remains on the legacy profile path, P/R positions remain unchanged, and the production driver configuration remains MRES=3/DEDGE."),
    2190: TestCatalogEntry(2190, "Z speed ladder 30 kHz", "Three long-Z out/return/home repetitions with complete TIM10 ISR timing at 30 kHz logical rate."),
    2191: TestCatalogEntry(2191, "Z speed ladder 40 kHz", "Three long-Z out/return/home repetitions with complete TIM10 ISR timing at 40 kHz logical rate."),
    2192: TestCatalogEntry(2192, "Z speed ladder 50 kHz", "Three long-Z out/return/home repetitions with complete TIM10 ISR timing at 50 kHz logical rate."),
    2193: TestCatalogEntry(2193, "Z speed ladder 60 kHz", "Three long-Z out/return/home repetitions with complete TIM10 ISR timing at 60 kHz logical rate."),
    2194: TestCatalogEntry(2194, "Z speed ladder summary", "Tier completion, final homes, production driver configuration, and P/R isolation."),
    2195: TestCatalogEntry(2195, "Z 35 kHz at 140k acceleration", "Three long-Z out/return/home repetitions at 35 kHz and 140,000 logical steps/s^2 with complete TIM10 ISR timing."),
    2196: TestCatalogEntry(2196, "Z 35 kHz at 100k acceleration", "Three long-Z out/return/home repetitions at 35 kHz and 100,000 logical steps/s^2 with complete TIM10 ISR timing."),
    2197: TestCatalogEntry(2197, "Z 40 kHz at 100k acceleration", "Three long-Z out/return/home repetitions at 40 kHz and 100,000 logical steps/s^2 with complete TIM10 ISR timing."),
    2201: TestCatalogEntry(2201, "Pressure hold leak", "Closed-loop pressure decay and correction effort."),
    2202: TestCatalogEntry(2202, "Pressure target cycling", "Repeated low/high target settling and pressure span."),
    2203: TestCatalogEntry(2203, "Pressure hysteresis", "Regulator motor repeatability and hysteresis span."),
    2210: TestCatalogEntry(2210, "Pressure idle stability", "Print/refuel sensor noise, drift, rejects, and safety faults while regulators are idle."),
    2211: TestCatalogEntry(2211, "Pressure regulator homing", "Print/refuel regulator homing repeatability after a fresh setup home."),
    2212: TestCatalogEntry(2212, "Print pressure hold", "Print regulator fresh-home 2 psi hold stability using production setpoint slew."),
    2213: TestCatalogEntry(2213, "Refuel pressure hold", "Refuel regulator fresh-home 2 psi hold stability using production setpoint slew."),
    2214: TestCatalogEntry(2214, "Print pressure cycling", "Print regulator same-direction low/high repeatability and transient over/under through adjacent 1 psi target steps using production setpoint slew."),
    2215: TestCatalogEntry(2215, "Refuel pressure cycling", "Refuel regulator same-direction low/high repeatability and transient over/under through adjacent 1 psi target steps using production setpoint slew."),
    2216: TestCatalogEntry(2216, "Print pressure hysteresis", "Print regulator fresh-home same-direction repeatability and informational approach-direction hysteresis at 2 psi."),
    2217: TestCatalogEntry(2217, "Refuel pressure hysteresis", "Refuel regulator fresh-home same-direction repeatability and informational approach-direction hysteresis at 2 psi."),
    2218: TestCatalogEntry(2218, "Print pressure step ladder", "Print regulator fresh-home settling and transient over/under through a 1, 2, 3, 2, 1 psi target ladder."),
    2219: TestCatalogEntry(2219, "Refuel pressure step ladder", "Refuel regulator fresh-home settling and transient over/under through a 1, 2, 3, 2, 1 psi target ladder."),
    2220: TestCatalogEntry(2220, "Refuel vacuum sensor shift", "Refuel pressure sensor atmospheric baseline before and after repeated -1 psi vacuum cycles."),
    2221: TestCatalogEntry(2221, "Refuel vacuum cycle repeatability", "Refuel regulator cycling between -1 psi and atmosphere with pressure, settle, and motor-position guards."),
    2401: TestCatalogEntry(2401, "Print valve pulse drop", "Print valve pulse pressure-drop repeatability."),
    2402: TestCatalogEntry(2402, "Refuel valve pulse drop", "Refuel valve pulse pressure-drop repeatability."),
    2403: TestCatalogEntry(2403, "Dual valve interaction", "Print/refuel pulse interaction and pressure-drop balance."),
    2473: TestCatalogEntry(2473, "Print valve 2 psi repeatability", "Print valve isolated 2 psi grouped 1500, 3000, and 4500 us pulses with Python-derived steady settled pressure-drop repeatability, pulse-width linearity, ringing, actuation latency, and regulator-position context."),
    2474: TestCatalogEntry(2474, "Refuel valve 2 psi repeatability", "Refuel valve isolated 2 psi grouped 1500, 3000, and 4500 us pulses with Python-derived steady settled pressure-drop repeatability, pulse-width linearity, ringing, actuation latency, and regulator-position context."),
    2475: TestCatalogEntry(2475, "Valve channel balance at 2 psi", "Python-derived print/refuel channel balance at 2 psi using the isolated grouped steady settled-drop trace analysis without additional valve actuation."),
    2476: TestCatalogEntry(2476, "Print valve 1500 us gap sweep", "Exploratory print valve 2 psi 1500 us pulse traces with Python-derived settled pressure-drop response versus post-ready settle gap."),
    2477: TestCatalogEntry(2477, "Refuel valve 1500 us gap sweep", "Exploratory refuel valve 2 psi 1500 us pulse traces with Python-derived settled pressure-drop response versus post-ready settle gap."),
    2478: TestCatalogEntry(2478, "Print valve gap controls", "Exploratory print valve 2 psi 3000 and 4500 us control traces at short and long post-ready settle gaps."),
    2479: TestCatalogEntry(2479, "Refuel valve gap controls", "Exploratory refuel valve 2 psi 3000 and 4500 us control traces at short and long post-ready settle gaps."),
    2501: TestCatalogEntry(2501, "Gripper closed seal decay", "Short dummy-head seal decay after valve burst."),
    2502: TestCatalogEntry(2502, "Gripper seal hold duration", "Longer dummy-head seal hold and decay behavior."),
    2503: TestCatalogEntry(2503, "Gripper seal repeatability", "Repeated dummy-head seal retention and span."),
    2510: TestCatalogEntry(2510, "Gripper static pressure matrix", "Python-derived dummy-head seal pressure-drop response for 1, 2, and 3 psi long regulator-quiet pressure challenges with refresh disabled, using one unmeasured conditioning pulse per pressure before five measured decimated traces per channel."),
    2511: TestCatalogEntry(2511, "Gripper deferred-refresh boundary", "Deferred refresh remains pending during idle and direct 3 psi pressure traces, is claimed exactly once after a production Printer dispense, rearms after pump-off, and delays the next dispense through the 3000 ms cooldown."),
    2512: TestCatalogEntry(2512, "Gripper raster motion stress", "A pending deferred refresh remains non-actuating during the Z-clearance-preflighted, homed, operator-confirmed 384-well XY raster and direct 3 psi pressure traces, followed by Z home and park."),
    2513: TestCatalogEntry(2513, "Gripper post-motion seal compare", "Python-derived pre/post raster 3 psi static seal comparison from decimated traces to detect motion-induced seal degradation."),
}


def test_catalog_entry(test_id: int) -> TestCatalogEntry:
    parsed = int(test_id)
    return TEST_CATALOG.get(
        parsed,
        TestCatalogEntry(parsed, f"Diagnostic {parsed}", "Diagnostic behavior defined by the manifest."),
    )


__all__ = ["TEST_CATALOG", "TestCatalogEntry", "test_catalog_entry"]
